// Page component for a single blog post, rendered at /posts/[id]
import Layout from '../../components/layout'; // Shared page layout (header, footer, container)
import { getAllPostIds, getPostData } from '../../lib/posts-json'; // Data helpers for static generation
import Head from 'next/head'; // Allows adding elements to the <head> (e.g., <title>)
import Date from '../../components/date'; // Reusable date formatting component
import utilStyles from '../../styles/utils.module.css'; // CSS Modules with utility classes

// Build-time data fetch for an individual post.
// Next.js calls this for each path generated by getStaticPaths.
export async function getStaticProps({ params }) {
    // Fetch post content and metadata by id (reads markdown, parses frontmatter, converts to HTML)
    const postData = await getPostData(params.id);
    // Provide the fetched data to the page component via props
    return {
      props: {
        postData,
      },
    };
  }
export async function getStaticPaths() {
  // Return all possible post routes, e.g., [{ params: { id: 'my-post' } }, ...]
  const paths = getAllPostIds();
  return {
    // Pre-render only these paths at build time
    paths,
    // 404 for any route not returned by getAllPostIds
    fallback: false,
  };
}
export default function Post({ postData }) {
    return (
      <Layout>
        <Head>
          {/* Set the document title to the post title for better SEO */}
          <title>{postData.title}</title>
        </Head>
        <article>
          {/* Post title */}
          <h1 className={utilStyles.headingXl}>{postData.title}</h1>
          {/* Human-friendly formatted publication date */}
          <div className={utilStyles.lightText}>
            <Date dateString={postData.date} />
          </div>
          {/* Render the post's HTML content generated from Markdown. */}
          {/* Note: dangerouslySetInnerHTML is required to inject trusted HTML. */}
          <div dangerouslySetInnerHTML={{ __html: postData.contentHtml }} />
        </article>
      </Layout>
    );
  }